### ISSUE TITLE
Temporarily ban and formerly reprimand for users that violated Brett's ceasefire request

### ISSUE THREAD

**Issue by tiran** [python/steering-council#32] opened 2020-07-03 14:02 UTC
In his message https://mail.python.org/archives/list/python-dev@python.org/thread/B2CFXHM2ND3KOYGLTBOYK4H2VMGRZT7J/ Brett asked users to refrain from replying to the PEP 8 discussion thread for 24 hours. His request has been violated by several users, PSF members, and Python core developers. I like to request swift and strong action from the steering council on the violation of Brett's request and propose following actions:

1. Temporarily ban user from python-dev for one month
2. After one month users may appeal and request a removal of ban with a written apology.
3. Give a formal warnings for all core developers that have violated the request. 

Personally I would even go so far and issue "strike one" for violators. (strike three = your are out)

In my humble opinion a swift and strong reaction is required to salvage what is left of python-dev. Some core developers have already been left and unsubscribed from python-dev mailing list. I will unsubscribe unless the situation improves and violators are disciplined. I'm holding my fellow core developers and PSF members to an even higher standard. Core developers and PSF members should lead by example and strive for excellence.

**Comment by vstinner** [comment] 2020-07-03 14:04
> Temporarily ban user from python-dev for one month

IMO one week would be enough to cool down python-dev.

**Comment by Ricyteach** [comment] 2020-07-03 20:15
Hello,

Important: at least one participant in that thread (me) is not subscribed to dev, only ideas. This might be the same for others. The thread was cross posted to both lists early on, and so any ideas-only users would not have received Brett's request.

Thanks,
Rick.

**Comment by pradyunsg** [comment] 2020-07-03 20:30
@Ricyteach this issue's first post does not mention python-ideas, and is requesting action on the python-dev mailing list.

The final sentence in the first post is seems to be the rationale on why this request is for only python-dev.

**Comment by brettcannon** [comment] 2020-07-03 21:37
@Ricyteach my email was only sent to python-dev and that was on purpose; python-ideas was left in moderation mode and not removed until us moderators felt the PEP 8 thread had died down. So there was actually no way anyone on python-ideas could even violate the request I made on python-dev since the moderators would not have let such an email through to begin with.

**Comment by Ricyteach** [comment] 2020-07-03 21:42
Thank you I was really concerned I'd potentially unknowingly violated that request.

**Comment by njsmith** [comment] 2020-07-05 20:33
I'd like to second @tiran's request for some kind of clear, concrete action here.

I don't know how that thread developed or what specifically prompted Brett's post, because after the first few messages I had to take anti-panic-attack medication and set my email client to hide all followups for self-protection. It was a bit of a wake-up call for me. Participating on python-dev has always been bruising and unpleasant, but I've gotten used to treating that as "normal". I care about the language and community, I want to help make them better, and as a long-time OSS contributor I have highly-developed martyrdom muscles – I will absolutely keep contributing to projects up to the limit of what I'm physically capable of. But at this point... I just don't know if I can stay subscribed.

An effectively unmoderated forum like this just isn't workable or humane anymore (if it ever was). Please, please, do something.

**Comment by warsaw** [comment] 2020-07-05 23:37
One option that @brettcannon has been advocating for a while now is to move python-dev to discuss.python.org because of its more flexible moderation controls.  I haven't been in favor of that, but if python-dev is irretrievably dysfunctional, that's a far better option than allowing that dysfunction to break the community.

**Comment by gvanrossum** [comment] 2020-07-06 00:48
I felt the same as Nathaniel (perhaps worse since (a) I merged the offending commit and (b) I was at the same time the target of a fire-hose of feedback on PEP 622).

I don't want to comment on what to do. But I personally wouldn't want to move to discuss.python.org. I depend on my GMail archive of all sorts of Python mail. (My life is somewhat similar to what Linus Torvalds apparently said today, although I am no longer the authority who says "no". :-)

**Comment by vstinner** [comment] 2020-07-06 09:43
I dislike closing python-dev if favor of Discourse. IMHO what we need right down is to put python-dev under very strong moderation. I suggest to send a new rule: the discussion on the PEP 8 is closed for 1 month. Anyone who will not respect this simple rule will see their account disabled for 1 week. One week later, if the same person misbehaves again: account disable for 1 month. If this person is a desperate case and continue to mishave after that, the person will be banned form python-dev.

I'm also open to consider reading old emails and disable account of people of misbehaved last weeks.

python-dev moderators would not have to justify themselves about what "misbehave" means. There is no need to notify persons who have their account disabled.

Account disabled means: not allowed to post any email for the duration of the ban.

Honestly, too many people already crossed the line, there is no need to try to be nice, explain and communicate. It's too late.

Sadly, I will not be available next weeks, and so I'm not available to moderate the list.

**Comment by vstinner** [comment] 2020-07-06 09:44
FYI I skipped **all** emails bout PEP 8 because I know that there are "very negative" and I'm not in the mood to be able to handle that.

**Comment by njsmith** [comment] 2020-07-06 12:33
I think ultimately, we need two things: moderators who are willing to actively step in before things reach a crisis + policies and tools that make it possible for them to do that. A lot of why I despair over python-dev in situations like this is that once the torrent starts, I know that there's nothing that will or even can be done to stop it. I don't see how this can be fixed while keeping it a mailing list, because the moderation tools are just so poor – the most basic interventions like locking a thread or hiding posts are difficult-to-impossible. Making a public show of punishing folks who ignored Brett's request would help a bit because it would make people more likely to respect future requests, and might be a good idea anyway because consequences are important, but fundamentally I just don't see how this can be fixed while keeping it a mailing list.

I don't really care what the replacement is as long as it fixes that problem.

FWIW, as a concrete data point, if the PEP 8 thread had been on discuss.python.org, I would have locked it within the first few messages and then consulted the SC/conduct-wg to figure out what to do next.

@gvanrossum 
> But I personally wouldn't want to move to discuss.python.org. I depend on my GMail archive of all sorts of Python mail.

Huh, my GMail does have an archive of all posts on discuss.python.org, because I have it set to email me every post in the categories I'm subscribed to, so GMail search works well for me. (I guess it's not 100% perfect because it doesn't incorporate post-hoc edits, but so far this hasn't been a problem.) I'm not sure exactly what settings you need to make this happen, but I'd be happy to help you figure it out if you want.

**Comment by vstinner** [comment] 2020-07-06 12:36
> FWIW, as a concrete data point, if the PEP 8 thread had been on discuss.python.org, I would have locked it within the first few messages and then consulted the SC/conduct-wg to figure out what to do next.

People created dozens of "PEP 8" threads.

**Comment by pitrou** [comment] 2020-07-06 12:37
"Actively step in" is what Brett did (I don't know if he's formally a moderator, but he did step in anyway). After his request, the thread cooled down and most activity stopped.

The most recent messages have been harmless (though pointlessly off-topic) discussion about specifics of the English language(s). They certainly aren't bringing anything constructive. But you don't have to trust my judgement ;-)

**Comment by njsmith** [comment] 2020-07-06 12:47
@vstinner I'm guessing that that would have been a lot fewer if the original thread hadn't continued to grow and trigger reactions. And if people do circumvent a thread lock by starting a new thread, then that's pretty straightforward to deal with – now the issue isn't the content, it's that they're intentionally breaking the rules, so you can go straight to deleting the new threads, putting their account on timeout, that kind of thing.

**Comment by brettcannon** [comment] 2020-07-14 23:38
To be very clear, my email was sent by me personally and not on behalf of the SC so that I could act faster than I could get email confirmation people were okay with me saying what I did (although I very much expect everyone else on the SC would have agreed). I worded that email carefully so it didn't mislead that I was speaking on behalf of the SC. Because of that I don't know what people really violated beyond my personal ask to just stop talking for a while to let things settle down.

And @njsmith is right that if this had been on discuss.python.org a moderator would have locked the thread until the Conduct WG could make a call. Plus the thread would not have forked like it did into a ton of separate threads. There also would have been the possibility of individual messages being removed while letting the discussion stay civil.

Regardless, I agree that something needs to change. Whether that is proactive moderation or people being more clearly told what is and is not acceptable is open for debate.

And I will say the SC is working on a reaction to all of this, but I don't want to go into further detail until it is made public (the timing really sucks due to holidays for folks).

**Comment by brettcannon** [comment] 2020-07-20 18:42
We discussed this request on the SC and we have decided that there isn't anything specifically to do since my email was personal in order to act as fast as possible. There may be an email, though, about the thread itself that's forthcoming.

**Closed by brettcannon** 2020-07-20 18:42 UTC
